### ISSUE TITLE
"New Record!" display

### ISSUE THREAD

**Issue by CrackedP0t** [RedInquisitive/Super-Haxagon#11]
It would be cool if, when you surpassed your old time, the game informed you. I was thinking maybe print the text under the time when playing, and in the game over screen when you beat your record.

It doesn't look hard to implement; I'd be happy to do it

**Comment by RedTopper** [comment]
Heh, I actually had code planned for  that but lazy me didn't  implement it. 

Anyway, if  you want to implement it, you'll need to understand these code snippets:
https://github.com/RedInquisitive/Super-Haxagon/blob/01c396d12373ea24057c0c088c5dc7e068859858/source/main.c#L124-L130
and
https://github.com/RedInquisitive/Super-Haxagon/blob/01c396d12373ea24057c0c088c5dc7e068859858/source/logic.c#L386
and 
https://github.com/RedInquisitive/Super-Haxagon/blob/01c396d12373ea24057c0c088c5dc7e068859858/source/draw.c#L423-L442

so   go  ahead!

**Comment by CrackedP0t** [comment]
Implemented in https://github.com/RedInquisitive/Super-Haxagon/pull/13

**Comment by RedTopper** [comment]
gotch'a

**Comment by RedTopper** [comment]
Hold up a second, come back! Is the NEW RECORD! thing supposed to pulse a few times, or keep pulsing forever?

Just wanted to know to check if it was a bug or not.

**Comment by CrackedP0t** [comment]
Oh, yeah, when playing it only pulses twice on purpose. On the game over screen it should pulse forever. The constant `PULSE_TIMES` controls the number of times on the play screen.

**Comment by RedTopper** [comment]
> Oh, yeah, when playing it only pulses twice on purpose. On the game over screen it should pulse forever.  The constant PULSE_TIMES controls the number of times on the play screen.

I think (in citra at least) on the game over, it only pulses twice, maybe 3 times (each pulse is lighter than the last)

**Comment by CrackedP0t** [comment]
OK, the algorithm was messed up and it was getting fainter over time. #14 should fix it. (And look a lot nicer)

**Comment by RedTopper** [comment]
yuuup, so much better!
