### ISSUE TITLE
Specifications for custom music?

### ISSUE THREAD

**Issue by Boured** [RedInquisitive/Super-Haxagon#12]
I'm probably blind but I've tried exporting custom wavs in both 32bit and 16bit pcm and none of them play at all. I know it isn't my DSP as when I put the default music it plays fine. What do I need to do in order for them to play in Super Haxagon?

If I'm being an Idiot I'm sorry.

Also I'm trying to replace the music for the default levels if your wondering.

**Comment by RedTopper** [comment]
Alright, so as  far as I  know, some people  have  found that stereo does not  work. Try converting it to signed 16  bit PCM mono and give  that a  shot.

You aren't being an idiot, you're fine! I don't think it's  mentioned anywhere. If you need to know the custom tracks for each level, check here: https://github.com/RedInquisitive/Haxa-Editor/tree/master/hexlevels (the XML files will  show you the way)
