### ISSUE TITLE
windows problem:

### ISSUE THREAD

**Issue by cooolgamer** [RedInquisitive/Super-Haxagon#16]
I can't open the game, it say me "the file VCRRUNTIME140_1.dll is missing.
Please help me,
thanks.

**Comment by RedTopper** [comment]
Looks like you might be missing the Visual C++ Runtime for Windows. Could you try installing the latest version here?
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads
I didn't think I linked against it but I must have. It's probably required for SFML to work.

**Comment by cooolgamer** [comment]
Thanks you! it work :) I just need help for compiling now lol

**Comment by RedTopper** [comment]
Sweet, I'll put a note in the readme and close this!
