### ISSUE TITLE
compilation problem2

### ISSUE THREAD

**Issue by cooolgamer** [RedInquisitive/Super-Haxagon#19]
hello, I tryied with msys2 and it worked for 3ds examples but not for super haxagon:
![image](https://user-images.githubusercontent.com/64099608/99239973-19060980-27fc-11eb-9295-e277c93abc52.png)
here is the error. Can you help me?
thanks.

**Comment by RedTopper** [comment]
Dang, it gets all the way to linking and then it chokes. I have a feeling you might either be missing a library (unlikely, one of the .o files would have failed to generate if that was the case) or your version of ld might be wrong.

Can you run `ld -v` and tell me its output?

**Comment by cooolgamer** [comment]
![image](https://user-images.githubusercontent.com/64099608/99269082-394abe00-2826-11eb-977d-a9d7177c1d4b.png)
Same on windows cmd

**Comment by RedTopper** [comment]
Ok, that's good. Your `make` seems to match mine.

Can you try running `ld -v` and `gcc -v` without `make` in front of it?

**Comment by cooolgamer** [comment]
![image](https://user-images.githubusercontent.com/64099608/99272136-b9bdee80-2827-11eb-97e0-c342ec84aee1.png)
not found...

**Comment by RedTopper** [comment]
Alright, let's try this.

Edit the line here:
https://github.com/RedTopper/Super-Haxagon/blob/master/Makefile#L16
to say
`BUILD_FLAGS_CXX := -std=gnu++17 --verbose`

Then run
`make clean`
and then
`make TARGET:=3DS 2> compile.txt`

Once the command errors, attach compile.txt here and I'll take a look at it.

**Comment by cooolgamer** [comment]
[CMakeLists.txt](https://github.com/RedTopper/Super-Haxagon/files/5548541/CMakeLists.txt)
here is it

**Comment by RedTopper** [comment]
Oops, wrong file. Did running that last command make a file called `compile.txt` in the same directory you found that one?

**Comment by cooolgamer** [comment]
nope

**Comment by cooolgamer** [comment]
no... No compile.txt

**Comment by RedTopper** [comment]
Are you sure you're running that exact command? If it's not producing an output then I'm not sure what's up. Make sure you edited the correct files and included the `2> compile.txt`, then make sure you are running it in MSYS not in cmd

**Comment by bdemg** [comment]
Hi, I'm having that exact same problem, the compilation dies when making the .elf. I tried making the compile txt and got this:
[compile.txt](https://github.com/RedTopper/Super-Haxagon/files/5825450/compile.txt)
Did you guys found out what was the error?

**Comment by RedTopper** [comment]
Looking at your build log, I see that your not building with msys (or your buildtools are outside of the msys root directory). This might not be a problem, but just something to keep in mind. For reference, my libctru is in ` C:/msys64/opt/devkitpro/libctru/include` and yours is in ` C:\devkitPro/libctru/include`. 

The more likely issue is that I see ` C:/msys64/opt/devkitpro/portlibs/3ds/include` missing when you are building. Perhaps you are missing a portlib?

**Comment by bdemg** [comment]
I managed to fix it, I think that the buildtools being outside of the msys directory was the problem. Also I was missing some tools like smdhtool and banner tool

**Comment by RedTopper** [comment]
Sweet, glad you were able to solve it! If anyone else happens to have an issue compiling, feel free to open a new issue.
