### ISSUE TITLE
Editor should maybe have its own repo

### ISSUE THREAD

**Issue by videah** [RedInquisitive/Super-Haxagon#2]
I feel having the editor in this repo could clutter it a bit, it would probably be wise to give it its own repo.

**Comment by RedTopper** [comment]
Oh! It didn't look that cluttered to me :laughing:.  I'll quickly explain the level editor though. It's going to be a console based Java app that'll write out binary files for the patterns. It won't be something huge, just a convenience in development (so I don't have to write a bunch of hex).

I'll keep this open in case I change my mind.

EDIT: I won't do this for now. If it gets big (It won't I hope) then it'll move
