### ISSUE TITLE
Audio doesn't play on linux

### ISSUE THREAD

**Issue by fisik-yum** [RedInquisitive/Super-Haxagon#21]
When I run the Linux build (Ubuntu 20.10), the Game plays fine, but sound is nonexistent. I can play the selected mode fine, but when I scroll through the menus the game just crashes. I've pasted part of the terminal output.

```An internal OpenAL call failed in SoundSource.cpp(196).
Expression:
   alGetSourcei(m_source, AL_SOURCE_STATE, &status)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundStream.cpp(317).
Expression:
   alSourcePlay(m_source)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

An internal OpenAL call failed in SoundStream.cpp(329).
Expression:
   alGetSourcei(m_source, AL_BUFFERS_PROCESSED, &nbProcessed)
Error description:
   AL_INVALID_OPERATION
   The specified operation is not allowed in the current state.
```

Also, this isn't related but is it normal to run the game as superuser?

**Comment by fisik-yum** [comment]
SOLVED. The Game creates the directory sdmc/ without list nor access permissions, which causes the problems that I mentioned earlier. I can now run the game without root and sound works fine!

**Comment by RedTopper** [comment]
Just to make sure if you restart the game in a directory that doesn't have `sdmc` as a standard user, it creates the directory `sdmc` with r/w permissions right? I can sneak in a call that sets permissions in [PlatformLinux.cpp](https://github.com/RedTopper/Super-Haxagon/blob/d3b4a9208dc9505a2890712fc639afaaa6e97863/source/Driver/Linux/PlatformLinux.cpp) but as you said it seems like the issue was just starting it as root on first launch.

If permissions aren't set correctly though I'll make sure it's done right!

**Comment by fisik-yum** [comment]
Edit: Made stuff a bit more clear.

The root thing was my fault. I started the program with root on first launch and had the said problem, but it happens without root.
When you launch for the first time [no root], `sdmc/` is created, but is an unreadable directory. I just had to modify `sdmc/` 's permissions to allow its contents to be listed, and then the executable could launch. Seems to be a problem with permissions to list files in said folder. Hope this helps.


Sorry if I'm mixing things up.

**Comment by RedTopper** [comment]
Ok, I'll see if I can get around to building and testing on Linux to see if I can reproduce it. Optimally you shouldn't need to edit permissions to get things working.

(As a reminder to myself I'll re-open this issue)

**Comment by RedTopper** [comment]
Think you could try this binary? I added a 0 to the `mkdir("./sdmc", 0755);` to make it octal. I haven't tested it because my ubuntu install appears to be currently broken.
[SuperHaxagon.zip](https://github.com/RedTopper/Super-Haxagon/files/6145304/SuperHaxagon.zip)

**Comment by fisik-yum** [comment]
Tried it and works fine! `sdmc` is created without any problems and the game launches and plays fine.

**Comment by RedTopper** [comment]
Ayyy, turns out it was a silly mistake on my part. I'll go ahead and commit that small change but I won't make a new official build until I get my new level pack working. 

Thanks for reporting this!
