### ISSUE TITLE
Windows 7: Game crashes almost immediately

### ISSUE THREAD

**Issue by sdasda7777** [RedInquisitive/Super-Haxagon#22]
When using Windows 7, the game crashes almost immediately after launch.
The game launches, (blank) window is created, "Open Haxagon" voice is played. Then it crashes. I think I have all the necessary libraries, but I'm not completely sure to be honest.

![obrazek](https://user-images.githubusercontent.com/17746796/159163482-42bbc8fa-c9c0-425b-9202-de9abaf07157.png)

**Comment by sdasda7777** [comment]
I tried to compile it myself, hoping I could investigate bit deeper, but unfortunately it seems cmake for Windows is broken. I would appreciate a lot if you could look into this, though.

**Comment by RedTopper** [comment]
>  but unfortunately it seems cmake for Windows is broken.

Shoot, I wonder what's causing that? I only have a Windows 10 machine that I use to build SuperHaxagon so I haven't looked at all into supporting Windows 7.

With that said, I noticed you are using "performance" for your visual effects on windows 7. SuperHaxagon uses OpenGL for rendering, so perhaps something is wrong with your video driver or you do not have a compatible openGL device in your system? This could occur if you are trying to run the game in a VM for example.

**Comment by sdasda7777** [comment]
> Shoot, I wonder what's causing that? I only have a Windows 10 machine that I use to build SuperHaxagon so I haven't looked at all into supporting Windows 7.

I don't think it has anything to do with this specific project. To me it genuinely seems like cmake is parsing commandline arguments incorrectly, making it impossible for me to generate a project.

> With that said, I noticed you are using "performance" for your visual effects on windows 7. SuperHaxagon uses OpenGL for rendering, so perhaps something is wrong with your video driver or you do not have a compatible openGL device in your system? This could occur if you are trying to run the game in a VM for example.

I'm honestly not sure about this. I don't see supported OpenGL version on Intel's website for this processor, so this it might be correct. Do you have any ideas how I could test this?

**Comment by sdasda7777** [comment]
Dang, it seems you were absolutely correct. I tried launching a game in Dolphin with renderer set to OpenGL, and it errored out, even though it worked when it was set to DirectX.

Kinda shame, but it seems this isn't a bug.

Although, could you maybe add a check and a warning in this case?

**Comment by RedTopper** [comment]
> Dang, it seems you were absolutely correct. I tried launching a game in Dolphin with renderer set to OpenGL, and it errored out, even though it worked when it was set to DirectX.

Oof! I'll update the readme with that information, it's good to have this documented somewhere.

What CPU do you have? It seems so odd for a gpu (even if integrated) to not have OpenGL support. You can get that info by running `dxdiag`

> Although, could you maybe add a check and a warning in this case?

I should be able to, yeah.

**Comment by sdasda7777** [comment]
> What CPU do you have? It seems so odd for a gpu (even if integrated) to not have OpenGL support. You can get that info by running `dxdiag`

The processor in this PC is first gen Intel i5. Yeah, it's really old, but it can still handle browser, video playback and even some lighter games (it has no problem emulating Wii in Dolphin).

**Comment by sdasda7777** [comment]
Actually the original game runs fine, and I just noticed it seems to use OpenGL also. I guess there is support for some OpenGL version here, then, just not a sufficient one.
