### ISSUE TITLE
Issues on Linux

### ISSUE THREAD

**Issue by IonicPixels** [RedInquisitive/Super-Haxagon#25]
Using the native Linux release doesn't necessarily work. Upon opening the application file, the game crashes, and I get an alert that the process had crashed: 
![image](https://user-images.githubusercontent.com/72478475/221004582-31c6188b-351d-4570-99e2-58c937d58f9e.png)

However, I can force the game open using my terminal, though that causes the game audio to fail: 
![image](https://user-images.githubusercontent.com/72478475/221005162-f11fd857-0e30-41e5-8657-91f570d59357.png)

I used wine to load the Windows release of the game, and in doing so there were no problems:
![image](https://user-images.githubusercontent.com/72478475/221007991-071280fc-c2be-462a-a2f3-3c64e2a8a335.png)

My guess is that it's an issue of the permission locked `sdmc` directory in the Linux release, the contents cannot even be seen unless you use `ls` with root permissions, as the folder locked from read/write access to the user. 
![image](https://user-images.githubusercontent.com/72478475/221008525-97aa59ff-9d97-44fa-8cb7-cc3c45f75ec2.png)
![image](https://user-images.githubusercontent.com/72478475/221009323-4256f0f9-e033-45c3-ba4e-205548ef9fe3.png)

I forcefully deleted the pre-made `sdmc` directory, remade it, and then tried reloading Super Haxagon. The process did not instantly crash after loading, but it was not responding, it eventually crashes, however. The same thing were to happen if I use the scores.db from the Windows release.

Here is my system information, if it is needed:
![image](https://user-images.githubusercontent.com/72478475/221008825-d6754d02-136f-458d-856b-00cf6eff7cdb.png)

I really hope I worded this well, it seems to just be a small little mistake that was made, and was unsure if you were aware of this.

**Comment by IonicPixels** [comment]
I should note: I am using the latest release version, and will test building from source myself soon to see if this is still a bug or just a useless PR because I didn't look at latest commit date and the latest release date.

**Comment by RedTopper** [comment]
Gah, yeah, this is #21 which I did fix. Unfortunately I was in the middle of re-writing a larger chunk of this project a few years ago and never got around to finishing it, so I didn't make a new release with just that fix.

**Comment by IonicPixels** [comment]
Ah yes, that makes sense, though I've come across another issue, where the source just won't build. Maybe I'm missing a dependency or something but I'm not sure: 
![image](https://user-images.githubusercontent.com/72478475/221370346-a6eab4fe-508a-40f5-a805-da094cee1be1.png)

**Comment by RedTopper** [comment]
Looks like you're just missing `zip` to do the final compression for uploading. The bin file should be in output for you to run uncompressed.

As for the warnings, seems like my compiler didn't previously warn for those. 

(Also love the Celeste wallpaper :slightly_smiling_face:)

**Comment by IonicPixels** [comment]
> Looks like you're just missing `zip` to do the final compression for uploading. The bin file should be in output for you to run uncompressed.

What exactly do you mean? I've followed all the build instructions in the README, yet I get this error, what `zip` are you talking about? the release `zip`?

> (Also love the Celeste wallpaper)

Ah, thank you!

**Comment by RedTopper** [comment]
> What exactly do you mean? I've followed all the build instructions in the README, yet I get this error, what zip are you talking about? the release zip?

Nah, the buildtools I use will throw all the built files in a .zip archive. If you want the final step to succeed you can just install zip (I don't use Arch but it'd probably be something like `sudo pacman -S zip`) and the Makefile will zip up the output folder for you. But if you just want to run the program it should be built in the `output` folder without that last step running.

`zip` isn't really required to build the application, it's just so I don't have to manually archive the output folder when I publish to GitHub.

**Comment by IonicPixels** [comment]
ahh I see, alright I've installed it and it built. Also yes, you are correct, the install command is indeed `sudo pacman -S zip`

**Comment by IonicPixels** [comment]
Well it built, but now there is a new problem to be dealt with:

https://user-images.githubusercontent.com/72478475/221463052-6bdcfc6f-3cd7-478d-af8a-b45f89e36c29.mp4

**Comment by RedTopper** [comment]
Can you run it in the console and post the output?

**Comment by IonicPixels** [comment]
![image](https://user-images.githubusercontent.com/72478475/221467274-7d6b2407-be31-4f81-bb98-b24134b69b87.png)

**Comment by IonicPixels** [comment]
Oh interesting, I copied the `romfs` directory from the Windows release and it worked without any problem

**Comment by RedTopper** [comment]
Yup, was about to write that. You can also copy it from the root directory of the repo.

**Comment by IonicPixels** [comment]
Alright, I'll leave you to close the issue if you'd like, but atleast it's working now
