### ISSUE TITLE
Recursive clone fails, github.com/Steveice10/buildtools repo is gone

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [RedInquisitive/Super-Haxagon#27]
Attempting to clone the repository with the `--recursive` flag fails, as the [Steveice10/buildtools](https://github.com/Steveice10/buildtools) repo seems dead.

**Comment by RedTopper** [comment]
That's not good - looks like another repo fell due to the Nintendo/Yuzu fallout.

I have a local copy that should allow this project to build (at least). I'll see if I can upload a copy of it to my GitHub account and re-link the repos. 

Thanks for catching this!

**Comment by RedTopper** [comment]
I have restored the following repos to my account:
https://github.com/RedTopper/bannertool (without history, could not find a full backup of this repo)
https://github.com/RedTopper/buildtools (with history)
You should be able to clone now, please give it a shot!

**Comment by HEPOSHEIKKI** [comment]
Fixed. Thanks for the quick response.
