### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by RedTopper** [RedInquisitive/Super-Haxagon#3]
### done
- [x] Base engine
- [x] Base render
- [x] Main menu
- [x] Score system
- [x] BGM
- [x] Sound Effects
- [x] Fonts and text rendering
- [x] Copy CIA to owncloud for fast development
- [x] Have a flag for BGM so you can build two versions.
- [x] Load levels from a file
- [x] Make walls move
- [x] Add collision to the game
- [x] Rewrite Polygon code to use the GPU
- [x] Make sure there are no memory leaks
- [x] Improve level editor
- [x] Game is 5% more trippy
- [x] Levels can have their own unique pattern now
- [x] Figure out why every 6th ish launch of the game causes it to hang on the Nintendo 3ds logo. 
- [x] Graphical Editor
- [x] Contemplate what license  I should use
- [x] More dynamic level loading
- [X] Level Up
- [X] Save score data 
- [X] Use OGG for sound files
- [X] Pulse to the beat

**Comment by rweichler** [comment]
Here's a minimal .ogg decoder: https://github.com/nothings/stb/blob/master/stb_vorbis.c

**Comment by RedTopper** [comment]
That's fantastic (and probably what we need!) but I have zero clues on how to implement that to communicate with the DSP firmware. Though if somebody else would like to give it a shot, they can go for it!

**Comment by c0merl** [comment]
Heya! Really cool Hexagon remake you did there, but I can't seem to get the music to work? I put the data/haxagon/*.wav folder into the 3ds folder. That's right isn't it?

**Comment by RedTopper** [comment]
@rweichler Well 3.5 years later I finally got good enough to have a clue on how to implement that library. Looks like I can finally close this, haha.
