### ISSUE TITLE
No music on anny of the versions

### ISSUE THREAD

**Issue by kristiansja** [RedInquisitive/Super-Haxagon#6]
Im using an old3ds and have 0 sound on anny of the versions

**Comment by RedTopper** [comment]
All versions require the NDSP firmware in order to play any audio. Have you tried dumping the NDSP firmware as described [here](https://gbatemp.net/threads/release-dsp-firmware-dumper.402108/)?

**Comment by kristiansja** [comment]
no, but thank you. I couldnt see anny reference to this in the readme file
