### ISSUE TITLE
This isn't really a real issue but..

### ISSUE THREAD

**Issue by NinjaBoyLao** [RedInquisitive/Super-Haxagon#7]
WHERE DID AUDIO.WAV (the banner tune) COME FROM I can't place it in the original soundtrack. Please post a link to wherever you got this? it's too damn catchy

**Comment by NinjaBoyLao** [comment]
Nevermind i found it, the banner source is from Open Hexagon, apparently the song name is either pi, or "Call me Katla". possibly by dunderpatrullen or bossfight.

**Comment by RedTopper** [comment]
Yup, you guessed it haha!
